apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: ci-cd-pipeline-
spec:
  params:
    - name: url
      value: <url>
    - name: docker-image
      value: <docker-image>
    - name: DOCKERFILE
      value: <DOCKERFILE>
    - name: gitops-repo
      value: <git-ops-repo>
    - name: path-to-deployment-template
      value: <path-to-deployment-template>
    - name: path-to-deployment
      value: <path-to-deployment>
  pipelineRef:
    name: ci-cd-pipeline
  workspaces:
    - name: git-source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
  serviceAccountName: pipeline-example-2
  serviceAccountNames:
    - taskName: gitops
      serviceAccountName: pipeline-example-2-gitops
  timeout: 1h0m0s
