apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gitops
spec:
  params:
    - name: docker-image
      type: string
    - name: path-to-deployment-template
      type: string
    - name: path-to-deployment
      type: string
    - name: gitops-repo
      type: string
  steps:
    - args:
        - >-
          set -e
          NEW_IMAGE=$(params.docker-image)
          echo Setting image to $NEW_IMAGE
          git clone -b master $(params.gitops-repo) gitops
          git config --global user.email "tekton@ibmcloud.com"
          git config --global user.name "Tekton Pipeline"
          cd gitops/
          cp ./$(params.path-to-deployment-template)
          ./$(params.path-to-deployment)
          sed -i "s|<DOCKER_IMAGE>|${NEW_IMAGE}|g"
          ./$(params.path-to-deployment)
          git add .
          git commit -m "Updating image name" --allow-empty
          git push
      command:
        - /bin/bash
        - "-c"
      image: registry.redhat.io/openshift-pipelines-tech-preview/pipelines-git-init-rhel8@sha256:3418326e0de53f5976532eb9431d7126c7f318774be92e3915e14a9f2eeaa09a
      name: gitops-step
      resources: {}
      workingDir: $(workspaces.output.path)
  workspaces:
    - name: output
