apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gitops
spec:
  params:
    - name: docker-image
      type: string
    - name: path-to-deployment-template
      type: string
    - name: path-to-deployment
      type: string
    - name: gitops-repo
      type: string
  steps:
    - script: >
        set -e

        echo Setting image to $(params.docker-image)

        git clone -b master $(params.gitops-repo) gitops

        git config --global user.email "tekton@ibmcloud.com"

        git config --global user.name "Tekton Pipeline"

        cd gitops/

        cp ./$(params.path-to-deployment-template)
        ./$(params.path-to-deployment)

        sed -i "s|<DOCKER_IMAGE>|$(params.docker-image)|g" ./$(params.path-to-deployment)

        git add .

        git commit -m "Updating image to $(params.docker-image)" --allow-empty

        git push
      image: image-registry.openshift-image-registry.svc:5000/openshift/tools
      name: gitops-step
      resources: {}
      workingDir: $(workspaces.output.path)
  workspaces:
    - name: output
