apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: node-api-pipeline
spec:
  params:
    - name: docker-image
      type: string
    - name: url
      type: string
    - name: DOCKERFILE
      type: string
    - name: gitops-repo
      type: string
    - name: path-to-deployment-template
      type: string
    - name: path-to-deployment
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.url)
        - name: revision
          value: master
        - name: submodules
          value: "true"
        - name: depth
          value: "1"
        - name: sslVerify
          value: "false"
        - name: deleteExisting
          value: "true"
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: git-source
    - name: test
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: unit-tests
      workspaces:
        - name: output
          workspace: git-source
    - name: build-push
      params:
        - name: docker-image
          value: $(params.docker-image)
        - name: DOCKERFILE
          value: $(params.DOCKERFILE)
      runAfter:
        - test
      taskRef:
        kind: Task
        name: build-push
      workspaces:
        - name: output
          workspace: git-source
    - name: gitops
      params:
        - name: docker-image
          value: $(params.docker-image)
        - name: path-to-deployment-template
          value: $(params.path-to-deployment-template)
        - name: path-to-deployment
          value: $(params.path-to-deployment)
        - name: gitops-repo
          value: $(params.gitops-repo)
      runAfter:
        - build-push
      taskRef:
        kind: Task
        name: gitops
      workspaces:
        - name: output
          workspace: git-source
  workspaces:
    - description: The git repo
      name: git-source
