apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: ci-cd-event-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: gitlab-binding
      name: ci-cd-pipeline-trigger-template
      template:
        name: ci-cd-pipeline-trigger-template
