apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: example-pipeline-2
spec:
  podTemplate: {}
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: github-binding
      name: example-pipeline-2-trigger-template
      template:
        name: example-pipeline-2-trigger-template
